name: Deploy External Repo to GitHub Pages
on:
  schedule:
    - cron: '15 2 * * *' # Startet jetzt jede Nacht um genau 02:15 Uhr UTC
  push:
    branches:
      - main  # Die Pipeline startet, wenn du in DIESEM Repo (x2) die YAML änderst
  workflow_dispatch: # Erlaubt dir, die Pipeline jederzeit manuell per Button zu starten

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout External Code
        uses: actions/checkout@v4
        with:
          repository: 'steppentaucher/Stundenplan' # HIER: Trage den echten Namen von Account 1 und dessen Repo ein
          ref: 'main'                  # Der Branch von Repo 1, den du klonen willst
          token: ${{ secrets.SYNC_TOKEN }} # HIER MITGEGEBEN: Der Schlüssel für das private Repo x1

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs # Sucht nach dem 'docs'-Ordner, der DRÜBEN im Repo x1 liegt
